os: linux
dist: trusty
sudo: required
language: node_js
node_js:
  - "8.11"
  - "9.11"

install:
- npm install

script: 
- node_modules/.bin/ganache-cli >/dev/null 2>&1 &
- npm run migrate
- npm run test
