os: linux
dist: trusty
sudo: required
language: node_js
node_js:
  - "8.11"
  - "9.11"

install:
- npm install -g truffle ganache-cli
- npm install

script: 
- ganache-cli >/dev/null 2>&1 &
- truffle migrate
- truffle testi
